name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install, lint, and test
      run: |
        npm ci
        npm run lint
        npm test
      env:
        CI: true